version: '3.9'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: gra
      MY_USER: lamboktulus1379
      MYSQL_PASSWORD: MyPassword_123
    volumes:
      - dbdata:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always

  myvotingapp:
    depends_on:
      - db
    build: ./
    ports:
      - "8080:5000"

volumes:
  dbdata: